Add Chainlink Oracle slippage check
IndexCoop/tenderly-bots pull request #11
Opened 2023-10-24 00:47 UTC by edkim

2023-10-24 17:36 UTC, edkim commented on test/trendIndexRebalance.test.ts
> +      expect(componentsAfter[0]).to.equal(wethAddress);
Testing that the component is removed from the setToken is better than checking weth.balanceOf() for 2 reasons:
1) balanceOf() can have dust from rounding. 
2) The keeper logic relies on the setToken having only 1 component at certain times (e.g. after rebalancing to 100% WETH)

2023-10-24 19:11 UTC, pblivin0x commented on test/trendIndexRebalance.test.ts
> +      expect(componentsAfter[0]).to.equal(wethAddress);
checks lgtm

2023-10-24 19:16 UTC, pblivin0x commented
couple items for my review
+ where can i find our `GlobalTradeExtension.trade()` call 
+ let's make sure we get notional vs. position units right in [our checks and calls](https://github.com/IndexCoop/index-protocol/blob/9e6e7d865add19ebfa4735b9743ebeb3b5029533/contracts/protocol/modules/v1/TradeModule.sol#L271-L279)
+ let's make sure we check decimal adjustments with tokens and oracle readings

2023-10-24 20:21 UTC, edkim commented
> couple items for my review
> 
> * where can i find our `GlobalTradeExtension.trade()` call
> * let's make sure we get notional vs. position units right in [our checks and calls](https://github.com/IndexCoop/index-protocol/blob/9e6e7d865add19ebfa4735b9743ebeb3b5029533/contracts/protocol/modules/v1/TradeModule.sol#L271-L279)
> * let's make sure we check decimal adjustments with tokens and oracle readings

2023-10-25 02:44 UTC, ckoopmann requested changes
Mostly LGTM.
Just some minor requests. Only "important" one would be to verify that we are protected against a stale chainlink oracle and adjust the code if not.

2023-10-25 02:44 UTC, ckoopmann commented on actions/lib/utils.ts
> +  const price = await oracleContract.latestRoundData();
We might want to add a check here to see how old the price is, to protect ourselves if the oracle is "stale" (or verify that chainlink has this protection built in already)

2023-10-25 02:44 UTC, ckoopmann commented on actions/lib/trendIndexRebalance.ts
> +    pendingTx = await globalTradeExtension.trade(
This might be a good point to add a log statement with the parameters so you can later debug more easily if something goes wrong.

2023-10-25 02:44 UTC, ckoopmann commented on test/trendIndexRebalance.test.ts
> +    const lowSlippage = -0.1; // -10% slippage
Interesting, does negative slippage even make sense in our case ? Maybe try to produce this error with a more "realistic value".

Also you could add a test for an outdated / stale chainlink price to make sure we have the expected behaviour there.

2023-10-25 15:01 UTC, edkim commented on actions/lib/utils.ts
> +
This code is copied over from our front-end https://github.com/IndexCoop/index-app/blob/8622b6cf0a63367daa0376f7e7956d6f83b20117/src/lib/utils/index.ts#L15

2023-10-25 15:11 UTC, edkim commented on actions/lib/trendIndexRebalance.ts
> +}
Here I convert BigNumbers of `sellQuantity` and `usdcWethPrice` into strings which are parsed to float, and then perform the multiplication and division. Then convert back to BigNumber.

Would it be better to keep everything as BigNumbers? I originally tried to do it that way but ran into overflow/underflows.

2023-10-25 15:25 UTC, edkim commented
@pblivin0x 
- The TradeExtension takes position units for `sendQuantity` and `minReceiveQuantity`. So I'm always using position units, and letting the TradeModule convert to notional units. 
- Decimal adjustments are done here https://github.com/IndexCoop/tenderly-bots/pull/11/files#r1371934918

2023-10-26 16:50 UTC, edkim commented on test/trendIndexRebalance.test.ts
> +    const lowSlippage = -0.1; // -10% slippage
I changed it to -1% slippage. If I use 0% slippage, there is no error bc the Uniswap price is slightly better than the Oracle price in that particular block.

2023-10-26 16:51 UTC, edkim commented on actions/lib/trendIndexRebalance.ts
> +    pendingTx = await globalTradeExtension.trade(
Good idea. Added.

2023-10-27 06:08 UTC, ckoopmann approved these changes
LGTM! Thanks for adding the oracle staleness check.
Might want to review the 72hour max delay as it seems quite long, but I'm not really sure what the right value should be on chainlink.

2023-10-27 17:18 UTC, pblivin0x approved these changes
LGTM 💯

2023-10-31 12:05 UTC, merged